export const data=[
    {name:"Asana",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"projectmanagement",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/asana.png"}
    ,
    {name:"Azure App",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"projectmanagement",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/azuredevops.png"},
    {name:"ClickUp",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"projectmanagement",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/azuredevops.png"}
    ,
    {name:"ClickUp",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"projectmanagement",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/clickup.png"},
    {name:"Zira",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"projectmanagement",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/jira.png"},
    {name:"Asana",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"projectmanagement",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/asana.png"},
    {name:"Asana",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"helpdesk",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/freshservice.png"},
    {name:"Asana",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"projectmanagement",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/asana.png"},
    {name:"Freshdesk",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"helpdesk",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/freshdesk.png"},
    {name:"zendesk",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"helpdesk",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/zendesk.png"}, {name:"Freshdesk",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"helpdesk",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/freshdesk.png"},
    {name:"zendesk",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"helpdesk",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/zendesk.png"},
    {name:"Freshdesk",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"helpdesk",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/freshdesk.png"},
    {name:"zendesk",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"helpdesk",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/zendesk.png"},
    {name:"Freshdesk",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"helpdesk",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/freshdesk.png"},
    {name:"zendesk",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"helpdesk",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/zendesk.png"}, {name:"Freshdesk",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"helpdesk",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/freshdesk.png"},
    {name:"zendesk",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"helpdesk",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/zendesk.png"},
    {name:"Freshdesk",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"helpdesk",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/freshdesk.png"},
    {name:"Airtable",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"collabration",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/airtable.png"},
    {name:"Google Calendar",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"collabration",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/googlecalendar.png"},
    {name:"Gmail",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"collabration",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/gmail.svg"},
    {name:"Google Docs",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"collabration",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/googledocs.png"},
    {name:"Slack",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"collabration",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/slack.png"},
    {name:"Drop Box",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"collabration",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/dropboxpaper.png"},
    {name:"Azure App",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"projectmanagement",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/azuredevops.png"},
    {name:"ClickUp",
    description:"Import all your Opportunities, Projects, Tasks, Contacts, Organizations and Leads to TimeCamp",
    type:"projectmanagement",img:"https://cdn-m.timecamp.com/img/greenbranding/integrations/azuredevops.png"},
]